apiVersion: v1
kind: Service              # 1
metadata:
  name: app-python-service
spec:
  type: LoadBalancer       # 2
  ports:
  - port: 5000               # 3
    protocol: TCP          # 4
    targetPort: 5000         # 5
  selector:                # 6
    app: app-python       # 7
